sudo: required

services:
  - docker

language: go
go:
  - tip

env:
- PROJECT_NAME=build-them-all

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential lintian -y
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh
  - curl -L https://raw.githubusercontent.com/mh-cbon/latest/master/install.sh | GH=mh-cbon/changelog sh -xe
  - curl -L https://raw.githubusercontent.com/mh-cbon/latest/master/install.sh | GH=mh-cbon/go-bin-deb sh -xe

install:
  - cd $GOPATH/src/github.com/mh-cbon/$PROJECT_NAME
  - glide install
  - go install

script: echo "pass"

before_deploy:
  - mkdir -p build/{386,amd64}
  - mkdir -p pkg-build/{386,amd64}
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/386/$PROJECT_NAME main.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/amd64/$PROJECT_NAME main.go
  - go-bin-deb generate -a 386 --version ${TRAVIS_TAG} -w pkg-build/386/ -o ${TRAVIS_BUILD_DIR}/$PROJECT_NAME-386.deb
  - go-bin-deb generate -a amd64 --version ${TRAVIS_TAG} -w pkg-build/amd64/ -o ${TRAVIS_BUILD_DIR}/$PROJECT_NAME-amd64.deb
  - rm -fr pkg-build/
  - mkdir -p pkg-build/{386,amd64}
  - docker run -v $PWD:/docker fedora /bin/sh -c "cd /docker && sh ./docker.sh ${TRAVIS_TAG} $PROJECT_NAME"
  - sudo chown travis:travis $PROJECT_NAME-{386,amd64}.rpm

deploy:
  provider: releases
  api_key:
    secure: MzJVLXom5Z/vwiL0lAWfe84d0OFWIVgjrIpyy6nMfnFDQiuJrtnpJVSxc59bBl8UyK+MBMgEnVWoIi3q6nKQZAEAKRZjqoXVzSh3uwtEhLBhSdBcP+wPnmtOBf3hOTQIx32hZWkz+bMIjKh3EDet+85VnznLT7zUtSgr5wKq35KGJuieWYvRhYy2DKsT4dqzeL8jQuGsefVM0gM7YArjx34LV7H7d7zlLtVSr8RJ/vDDwb8zOZxgmhd2ZrlK9Pe42XBModIAI1nFBNeuQuBikXYh7gexLE6Btgk3QnhwuzAGPW+WcAtclUaBcgBzBwPDPVAvz5ikydC0pdc8jimoDsVWNbHpqyuLBEBh2Vh8sy7/u3Ny9tqyl/K+K1FDyOKwEaFLS/Vmdvmj8phw1g2zNwbQ4n7OtiwNhy/CjTksqqhghhDCYeUdbZiNQE/6Jfz6z+pvMUt7SO2Y+ph3QNPxgpfx0xvyZ9Lk2CSU5Tu0iSOdhy/RrDGh17ZnI847dfnKZjluzugCpTprNtUXfQlnxXoGr4ihfv3ywlaSYUJ+dzTe+X8pwU0lUyGPIf+/fknvqB2RqwLAr0MFtk8DjC9pK4F5oZJEicnPvWHvtQ65H+h0GxlPDvTb2fDyMV1J4dXDzqqfqjmfbs3zOnuH6pIlZ2Ry26q930UCs9ykOuyC+PM=
  file:
    - $PROJECT_NAME-386.deb
    - $PROJECT_NAME-amd64.deb
    - $PROJECT_NAME-386.rpm
    - $PROJECT_NAME-amd64.rpm
  skip_cleanup: true
  on:
    tags: true
